# Site settings
title: Codana.me
extra_title: " | home of audio dev michael chadwick"
email: mike@neb.host
description: "code and audio (and audio code) developments by <a href='https://michaelchadwick.info'>michael chadwick</a>"
description_rss: "code and audio (and audio code) developments by michael chadwick"
url: "https://codana.me"
baseurl: ""
plugins: [jekyll-paginate]
paginate: 10
encoding: UTF-8
exclude: ["Rakefile", ".deploy.sh"]
include: ["mus.html", "net.html", "index_print.html"]
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
tag_page_layout: tag_page
tag_page_dir: tags

# Build settings
markdown: kramdown
permalink: pretty

# Custom Site settings
my_name: Michael Chadwick
gh_username: michaelchadwick
tw_username: mjchadwick
sc_n_username: nebyoolae
sc_mb_username: massive-battery
bc_username: nebyoolae
mc_link: https://michaelchadwick.info
gh_link: https://github.com/michaelchadwick
tw_link: https://twitter.com/mjchadwick
sc_n_link: https://soundcloud.com/nebyoolae
sc_mb_link: https://soundcloud.com/massive-battery
bc_neb_link: https://nebyoolae.bandcamp.com
bc_flv_link: https://flylikevenus.bandcamp.com
bc_fench_link: https://fench.bandcamp.com
bc_mcj_link: https://mcj.nebyoolae.com
bc_pyc_link: https://pureyellow.bandcamp.com
