#!/bin/sh

USER=mike
HOST=neb.host
DIR=/var/www/codana.me/public_html/

# build site
bundle exec jekyll b
# sync site, but exclude _apps
rsync -avz --delete-after --exclude=deploy --exclude=_apps _site/ ${USER}@${HOST}:${DIR}

exit 0
